/**
 * Icon set.
 *
 * Inline SVG rather than an icon font or an icon package: these are the only
 * ~20 glyphs the app needs, they inherit `currentColor` so they pick up chip and
 * button colors for free, and shipping them inline avoids a network request and
 * a flash of unstyled icons.
 *
 * Every icon is decorative and marked `aria-hidden`; the meaning always lives in
 * adjacent text or an aria-label on the control itself.
 */
import React from "react";

function Svg({ children, size = 18, strokeWidth = 1.8, ...rest }) {
  return (
    <svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth={strokeWidth}
      strokeLinecap="round"
      strokeLinejoin="round"
      aria-hidden="true"
      focusable="false"
      {...rest}
    >
      {children}
    </svg>
  );
}

// The app mark lives in its own file: it is generated by scripts/brand.py
// from the same geometry as the SVG assets, so it cannot drift from them.
// Import it from ./Insignia.jsx.

export const Search = (p) => (
  <Svg {...p}>
    <circle cx="11" cy="11" r="7" />
    <path d="M20 20l-3.6-3.6" />
  </Svg>
);

export const Filter = (p) => (
  <Svg {...p}>
    <path d="M3 5h18M6 12h12M10 19h4" />
  </Svg>
);

/** Crossed rifles — the browse/inventory view. */
export const Rifle = (p) => (
  <Svg {...p}>
    <path d="M3 7h13l3 3M3 7v3h9" />
    <path d="M12 10l-2 5-3 3" />
    <path d="M19 10l2-2" />
  </Svg>
);

export const Sites = (p) => (
  <Svg {...p}>
    <circle cx="12" cy="12" r="9" />
    <path d="M3 12h18M12 3c2.6 2.7 2.6 15.3 0 18M12 3c-2.6 2.7-2.6 15.3 0 18" />
  </Svg>
);

export const History = (p) => (
  <Svg {...p}>
    <path d="M3.2 10a9 9 0 1 1 .6 5" />
    <path d="M3 4v6h6" />
    <path d="M12 8v4l3 2" />
  </Svg>
);

export const Users = (p) => (
  <Svg {...p}>
    <circle cx="9" cy="8" r="3.4" />
    <path d="M2.5 20a6.5 6.5 0 0 1 13 0" />
    <path d="M16.5 5.3a3.4 3.4 0 0 1 0 5.4M18 14.2a6.5 6.5 0 0 1 3.5 5.8" />
  </Svg>
);

export const Mail = (p) => (
  <Svg {...p}>
    <rect x="2.5" y="5" width="19" height="14" rx="2.5" />
    <path d="M3 7l9 6 9-6" />
  </Svg>
);

export const Settings = (p) => (
  <Svg {...p}>
    <circle cx="12" cy="12" r="3.2" />
    <path d="M19.4 14a1.6 1.6 0 0 0 .3 1.8l.1.1a2 2 0 1 1-2.8 2.8l-.1-.1a1.6 1.6 0 0 0-2.7 1.1v.3a2 2 0 1 1-4 0v-.2a1.6 1.6 0 0 0-2.8-1.1l-.1.1a2 2 0 1 1-2.8-2.8l.1-.1A1.6 1.6 0 0 0 3.5 14H3a2 2 0 1 1 0-4h.2A1.6 1.6 0 0 0 4.3 7.2l-.1-.1a2 2 0 1 1 2.8-2.8l.1.1A1.6 1.6 0 0 0 10 3.5V3a2 2 0 1 1 4 0v.2a1.6 1.6 0 0 0 2.7 1.1l.1-.1a2 2 0 1 1 2.8 2.8l-.1.1a1.6 1.6 0 0 0 1.1 2.7h.4a2 2 0 1 1 0 4h-.2a1.6 1.6 0 0 0-1.4 1.2z" />
  </Svg>
);

export const Refresh = (p) => (
  <Svg {...p}>
    <path d="M20.5 11a8.5 8.5 0 1 0-.9 5" />
    <path d="M21 4v6h-6" />
  </Svg>
);

export const Play = (p) => (
  <Svg {...p}>
    <path d="M7 4.5l12 7.5-12 7.5z" fill="currentColor" strokeWidth="1.2" />
  </Svg>
);

export const Stop = (p) => (
  <Svg {...p}>
    <rect
      x="6"
      y="6"
      width="12"
      height="12"
      rx="2"
      fill="currentColor"
      strokeWidth="1.2"
    />
  </Svg>
);

export const Check = (p) => (
  <Svg {...p}>
    <path d="M4.5 12.5l5 5 10-11" />
  </Svg>
);

export const X = (p) => (
  <Svg {...p}>
    <path d="M6 6l12 12M18 6L6 18" />
  </Svg>
);

export const Warning = (p) => (
  <Svg {...p}>
    <path d="M12 3.5L22 20H2z" />
    <path d="M12 9.5v4.5M12 17.2v.1" />
  </Svg>
);

export const Clock = (p) => (
  <Svg {...p}>
    <circle cx="12" cy="12" r="9" />
    <path d="M12 6.5V12l3.5 2.2" />
  </Svg>
);

/** Downward price movement. */
export const TrendDown = (p) => (
  <Svg {...p}>
    <path d="M3 7l6.5 6.5 4-4L21 17" />
    <path d="M21 12v5h-5" />
  </Svg>
);

export const Tag = (p) => (
  <Svg {...p}>
    <path d="M3 11.5V4a1 1 0 0 1 1-1h7.5a1 1 0 0 1 .7.3l8.5 8.5a1 1 0 0 1 0 1.4l-7.5 7.5a1 1 0 0 1-1.4 0L3.3 12.2a1 1 0 0 1-.3-.7z" />
    <circle cx="7.5" cy="7.5" r="1.4" fill="currentColor" />
  </Svg>
);

export const Sparkle = (p) => (
  <Svg {...p}>
    <path d="M12 3l1.9 5.1L19 10l-5.1 1.9L12 17l-1.9-5.1L5 10l5.1-1.9z" />
    <path d="M18.5 15.5l.7 1.8 1.8.7-1.8.7-.7 1.8-.7-1.8-1.8-.7 1.8-.7z" />
  </Svg>
);

export const External = (p) => (
  <Svg {...p}>
    <path d="M14 4h6v6" />
    <path d="M20 4l-8.5 8.5" />
    <path d="M18 14.5V19a1.5 1.5 0 0 1-1.5 1.5h-11A1.5 1.5 0 0 1 4 19V8a1.5 1.5 0 0 1 1.5-1.5H10" />
  </Svg>
);

export const ChevronLeft = (p) => (
  <Svg {...p}>
    <path d="M15 5l-7 7 7 7" />
  </Svg>
);

export const ChevronRight = (p) => (
  <Svg {...p}>
    <path d="M9 5l7 7-7 7" />
  </Svg>
);

export const ChevronDown = (p) => (
  <Svg {...p}>
    <path d="M5 9l7 7 7-7" />
  </Svg>
);

export const Menu = (p) => (
  <Svg {...p}>
    <path d="M3 6h18M3 12h18M3 18h18" />
  </Svg>
);

export const Logout = (p) => (
  <Svg {...p}>
    <path d="M10 4.5H6A1.5 1.5 0 0 0 4.5 6v12A1.5 1.5 0 0 0 6 19.5h4" />
    <path d="M15 8l4 4-4 4M19 12H9" />
  </Svg>
);

export const Plus = (p) => (
  <Svg {...p}>
    <path d="M12 5v14M5 12h14" />
  </Svg>
);

export const Trash = (p) => (
  <Svg {...p}>
    <path d="M4 6.5h16M9.5 6.5V4.5h5v2" />
    <path d="M6.5 6.5L7.4 20a1 1 0 0 0 1 .9h7.2a1 1 0 0 0 1-.9l.9-13.5" />
    <path d="M10.5 10.5v6.5M13.5 10.5v6.5" />
  </Svg>
);

// A browser window: marks a site whose catalog only renders under headless
// Chrome. Informational, not a warning — see the chip in Sites.jsx.
export const Browser = (p) => (
  <Svg {...p}>
    <rect x="3" y="4" width="18" height="16" rx="2" />
    <path d="M3 9h18" />
    <path d="M6.5 6.5h.01M9 6.5h.01M11.5 6.5h.01" />
  </Svg>
);

export const Image = (p) => (
  <Svg {...p}>
    <rect x="3" y="4.5" width="18" height="15" rx="2" />
    <circle cx="8.5" cy="10" r="1.6" />
    <path d="M3.5 17l5-4.5 4 3.5 3-2.5 5 4" />
  </Svg>
);

/** Four panes: the card grid. */
export function Grid(props) {
  return (
    <Svg {...props}>
      <rect x="3" y="3" width="7.5" height="7.5" rx="1.5" />
      <rect x="13.5" y="3" width="7.5" height="7.5" rx="1.5" />
      <rect x="3" y="13.5" width="7.5" height="7.5" rx="1.5" />
      <rect x="13.5" y="13.5" width="7.5" height="7.5" rx="1.5" />
    </Svg>
  );
}

/** Rows with a leading marker: the list. */
export function List(props) {
  return (
    <Svg {...props}>
      <line x1="9" y1="6" x2="20" y2="6" />
      <line x1="9" y1="12" x2="20" y2="12" />
      <line x1="9" y1="18" x2="20" y2="18" />
      <circle cx="4.5" cy="6" r="1.2" />
      <circle cx="4.5" cy="12" r="1.2" />
      <circle cx="4.5" cy="18" r="1.2" />
    </Svg>
  );
}

/** Two bars: paused, resting, deliberately not running. */
export function Pause(props) {
  return (
    <Svg {...props}>
      <line x1="9" y1="5" x2="9" y2="19" />
      <line x1="15" y1="5" x2="15" y2="19" />
    </Svg>
  );
}
