"""Cherry's Fine Guns (cherrys.com).

A Greensboro, North Carolina dealer in collector and fine guns. Two pages are
read, long guns and handguns -- measured 2026-10-06 at about 67 and 48 -- which
mix antiques, curios and relics and used collector guns; the engraved,
commemorative, airgun and book pages are not.

**Each page is a table exported from a spreadsheet** ("generated by the
Internet Assistant Wizard for Microsoft Excel"): a row per gun, with the
shop's stock number, one paragraph describing it, the price, and numbered
links to its photographs. The stock number is the key. The paragraph is the
description, and its first clause -- "Ball & Williams Ballard Rifle" -- is the
title, because the shop writes no separate name.

**Read over plain HTTP.** Their HTTPS answers with a TLS handshake failure
(checked 2026-10-06), so ``https://`` is not an option rather than a
preference; the site has no forms and nothing is sent to it. There is no
robots.txt and no mailing list.
"""

from __future__ import annotations

import re
from urllib.parse import urljoin

from bs4 import BeautifulSoup

from .base import ScrapedItem, normalize_whitespace
from .catalog_pages import CatalogPagesScraper
from .storefront import parse_price

SITE_BASE = "http://www.cherrys.com/"

SOURCES = (
    {"category": "Long Guns", "url": f"{SITE_BASE}longguns.htm"},
    {"category": "Handguns", "url": f"{SITE_BASE}handguns.htm"},
)

_STOCK = re.compile(r"^[A-Z0-9][A-Z0-9-]{2,15}$", re.I)
#: The first clause: up to the first comma, unless that leaves too little to
#: say what the gun is.
_SHORTEST_TITLE = 12


def title_of(description: str) -> str:
    clauses = [part.strip() for part in description.split(",")]
    title = clauses[0]
    for clause in clauses[1:]:
        if len(title) >= _SHORTEST_TITLE:
            break
        title = f"{title}, {clause}"
    return title


def parse_page(html_text: str, page_url: str, category: str) -> list[ScrapedItem]:
    soup = BeautifulSoup(html_text, "html.parser")
    items: list[ScrapedItem] = []
    for row in soup.find_all("tr"):
        cells = row.find_all("td", recursive=False)
        if len(cells) < 3:
            continue
        stock = normalize_whitespace(cells[0].get_text(" ", strip=True))
        description = normalize_whitespace(cells[1].get_text(" ", strip=True))
        # The header row says STOCK#, which is not a stock number.
        if not _STOCK.match(stock) or not description or stock.upper().startswith("STOCK"):
            continue
        price = parse_price(cells[2].get_text(" ", strip=True))
        photos = [
            urljoin(page_url, str(link["href"]))
            for cell in cells[3:]
            for link in cell.select("a[href]")
        ]
        items.append(
            ScrapedItem(
                external_key=stock.upper(),
                url=f"{page_url}#{stock.upper()}",
                title=title_of(description),
                price=price,
                description=description,
                category=category,
                image_urls=photos,
                images_are_complete=True,
            )
        )
    return items


class CherrysScraper(CatalogPagesScraper):
    slug = "cherrys"
    name = "Cherry's Fine Guns"
    base_url = SITE_BASE
    description = "North Carolina dealer in antique, curio and collector long guns and handguns."
    default_interval_minutes = 1440
    newsletter_url = None
    newsletter_note = "No signup found on the site; checked 2026-10-06"
    shipping_note = "Long guns and antiques by UPS Ground; no firearm charge stated"
    shipping_source = "http://www.cherrys.com/ordering.htm"
    sources = SOURCES

    def parse_page(self, html_text: str, page_url: str, category: str) -> list[ScrapedItem]:
        return parse_page(html_text, page_url, category)
